/* Offline cache for the single-file build.
   CACHE is regenerated by tools/bundle.py on every build so that a new
   upload replaces the old cached copy instead of being ignored. */
const CACHE = 'ops-report-88539c189e28';
const ASSETS = ['./', 'index.html', 'manifest.webmanifest', 'icon-192.png', 'icon-512.png'];

self.addEventListener('install', (e) => {
  /* `cache: 'reload'` bypasses the browser's own HTTP cache.

     Without it the install fetches index.html through that cache and can store
     the copy the browser already had, so a phone keeps showing the previous
     build even though a new worker installed under a new cache name. */
  const fresh = ASSETS.map(u => new Request(u, { cache: 'reload' }));
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(fresh)).then(() => self.skipWaiting()));
});

/* A new worker normally waits for the old one to let go, which on a phone can
   mean never: the app is rarely closed properly. Settings asks for this so an
   update can be taken on demand. */
self.addEventListener('message', (e) => {
  if (e.data && e.data.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});

self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;
  e.respondWith(
    caches.match(e.request, { ignoreSearch: true }).then(hit => hit || fetch(e.request)
      .then(res => {
        if (res && res.status === 200 && res.type === 'basic') {
          const copy = res.clone();
          caches.open(CACHE).then(c => c.put(e.request, copy));
        }
        return res;
      })
      .catch(() => caches.match('index.html')))
  );
});
